"""Shared gateway-owned dataclasses passed across session boundaries."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    import numpy as np
    import torch


@dataclass
class SessionHandle:
    """Address returned to agent runners for a newly created gateway session.

    Attributes:
        session_id: Stable session identifier assigned by the caller.
        base_url: Per-session OpenAI-compatible ``/v1`` API root, or ``None``
            when the handle only needs to identify the session.
        reward_info_url: Per-session endpoint used by runners to attach reward
            metadata; this is a sibling of the OpenAI-compatible ``/v1`` root
            rather than part of that API.
    """

    session_id: str
    base_url: str | None = None
    reward_info_url: str | None = None


@dataclass
class Trajectory:
    """Token-level training trajectory produced when a gateway session finalizes.

    Attributes:
        prompt_ids: Prompt token IDs used to seed the trajectory.
        response_ids: Tokens generated by the model plus interstitial prompt
            tokens added during continuation turns.
        response_mask: Per-token labels for ``response_ids``; ``1`` marks model
            output and ``0`` marks interstitial context tokens.
        response_logprobs: Optional log probabilities aligned with
            ``response_ids``; continuation context tokens use ``0.0``.
        reward_info: Reward metadata attached through the session reward-info
            endpoint before finalization.
        reward_score: Optional scalar reward assigned by downstream training.
        num_turns: Chat-turn count materialized with the trajectory.
        routed_experts: Optional expert-routing data captured by the backend.
        multi_modal_data: Optional image/video data associated with the prompt.
        extra_fields: Gateway-owned extension fields, such as length finish
            metadata consumed by training adapters.
    """

    prompt_ids: list[int]
    response_ids: list[int]
    response_mask: list[int]
    response_logprobs: list[float] | None = None
    reward_info: dict[str, Any] = field(default_factory=dict)
    reward_score: float | None = None
    num_turns: int = 0
    routed_experts: torch.Tensor | np.ndarray | None = None
    multi_modal_data: dict[str, Any] | None = None
    extra_fields: dict[str, Any] = field(default_factory=dict)


@dataclass
class TurnCapture:
    """One generated turn exported from a live gateway session.

    Attributes:
        turn_index: Monotonic turn index within the session.
        seq: Monotonic event sequence id, used for exactly-once popping.
        prompt_ids: Context token IDs sent to the backend for this generation.
        response_ids: Generated token IDs for this turn.
        response_logprobs: Log probabilities aligned with ``response_ids``.
        assistant_msg: Decoded assistant message payload.
        finish_reason: OpenAI-compatible finish reason for this turn.
        messages: Normalized request messages used to build ``prompt_ids``.
        tools: Tool schemas bound to this request, when provided.
    """

    turn_index: int
    seq: int
    prompt_ids: list[int]
    response_ids: list[int]
    response_logprobs: list[float]
    assistant_msg: dict[str, Any]
    finish_reason: str
    messages: list[dict[str, Any]]
    tools: list[dict[str, Any]] | None = None
