# This file is used for old workflow, which changes name, to pass required tests.
# The file will be removed lately.
name: Python Backend CI

on:
  pull_request:
    branches: [ "main" ]
    types: [ opened, synchronize, reopened ]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    # tested in multi python version
    strategy:
      matrix:
        python-version: [ "3.11", "3.12" ]

    steps:
      - name: info
        run: echo "deprecation workflow, will be removed lately"
