"""Business event names shared by publishers and subscribers."""

GENERATION_FINISHED = "GenerationFinished"
GENERATION_PREPARED = "GenerationPrepared"
REPLICA_CAPACITY_CHANGED = "ReplicaCapacityChanged"
ROUTE_COMMITTED = "RouteCommitted"
SESSION_CLOSED = "SessionClosed"
SESSION_OPENED = "SessionOpened"
ADMISSION_ROUTER_OBSERVATION_SUBSCRIPTION = "admission-router-observations"
GATEWAY_SESSION_DIRECT_SUBSCRIPTION = "router-gateway-session-shadow"
GATEWAY_SESSION_STATE_SCOPE = "gateway_sessions"
GATEWAY_GLOBAL_FORWARDER_SUBSCRIPTION = "gateway-global-forwarder"
GATEWAY_TELEMETRY_SUBSCRIPTION = "gateway-telemetry-shadow"

__all__ = [
    "GENERATION_FINISHED",
    "GENERATION_PREPARED",
    "ADMISSION_ROUTER_OBSERVATION_SUBSCRIPTION",
    "GATEWAY_GLOBAL_FORWARDER_SUBSCRIPTION",
    "GATEWAY_SESSION_DIRECT_SUBSCRIPTION",
    "GATEWAY_SESSION_STATE_SCOPE",
    "GATEWAY_TELEMETRY_SUBSCRIPTION",
    "REPLICA_CAPACITY_CHANGED",
    "ROUTE_COMMITTED",
    "SESSION_CLOSED",
    "SESSION_OPENED",
]
